name: "Push image to ecr staging-v2-tokyo"

on:
  push:
    branches:
      - staging-v2-tokyo

env:
  EMPORUS_REGISTRY: ${{ secrets.AWS_ECR_ID_STAGING_V2 }}.dkr.ecr.${{ secrets.AWS_ECR_REGION_STAGING_V2_TOKYO }}.amazonaws.com
  EMPORUS_IMAGE_BASE: ${{ secrets.AWS_ECR_ID_STAGING_V2 }}.dkr.ecr.${{ secrets.AWS_ECR_REGION_STAGING_V2_TOKYO }}.amazonaws.com/emporus-hummingbot-backend-api
  EMPORUS_IMAGE: ${{ secrets.AWS_ECR_ID_STAGING_V2 }}.dkr.ecr.${{ secrets.AWS_ECR_REGION_STAGING_V2_TOKYO }}.amazonaws.com/emporus-hummingbot-backend-api:${{ github.sha }}
jobs:
  publish_image:
    name: Push Docker image to ECR
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: 'staging-v2-tokyo'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING_V2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING_V2 }}
          aws-region: ${{ secrets.AWS_ECR_REGION_STAGING_V2_TOKYO }}
      
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.EMPORUS_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING_V2 }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING_V2 }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          no-cache: true
          tags: |
            ${{ env.EMPORUS_IMAGE_BASE }}:staging-v2-tokyo
            ${{ env.EMPORUS_IMAGE }}